########## VECTOR-DB ###########
stability_test:
  stage: stability
  # dependencies: ["build_image"]
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-stability:1.2.4
  tags: 
    - task
  before_script:
    - docker/builder/tools/docker-info.sh
  script:
    # update submodule
    - ssh-keyscan -H git.moqi.ai > ~/.ssh/known_hosts
    - docker/builder/tools/submodule-update.sh
    # get image version
    - source docker/builder/tools/version.sh
    - mkdir -p /stability/Downloads/
    - cp tests/stability/helps/config/k8s-config /stability/Downloads/k8s-config
    # - cp $KUBECONFIG_CONTENT /stability/Downloads/cls-config
    - export KUBECONFIG=$KUBECONFIG:/stability/Downloads/k8s-config
    # deploy mqdb server in k8s
    - tests/stability/stability --run-in-k8s --namespace $GIT_BRANCH deploy --cluster-name one_s_two_r --mqdb-version $VERSION_STRING-$GIT_COMMIT
    - current_namespace=$(cat tests/stability/test_output/LOG/deploy-stability.log | grep 'current deploy namespace' | awk '{print $11}')
    # download test data
    - wget -P tests/stability/helps/data_files http://10.1.2.10/baidu-768-100w-angular.hdf5 > /dev/null 2>&1
    # - wget -P tests/stability/helps/data_files https://mqdb-release-1253802058.cos.ap-beijing.myqcloud.com/datasets/arxiv_small_payload.tar.gz > /dev/null 2>&1
    # setup lwd test, dataset: laion_5m_test_ip
    - tests/stability/stability --daemon lwd --dataset baidu_768_100w_angular --index MSTG --skip-exception-check
    # setup benchmark
    - tests/stability/stability --run-in-k8s --namespace $current_namespace benchmark --dataset baidu_768_100w_angular --mixed-query --parallel 32
    # check server status
    # [TODO]
    #   - Get Server Fatal Message
    #   - output grafana url
    #   - Correctness check
    - bash tests/stability/check_server_status.sh $current_namespace tests/stability/test_output/LOG/lwd-stability.log
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-stability"
    paths:
      - $CI_PROJECT_DIR/tests/stability/test_output
    when: always
  rules:
  # [TODO] Add more policy
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_IN_K8S == "stability"' # Trigger pipline during scheduled tasks