######################################## INTEGRATION TESTS ###################################
integration_test0:
  stage: failover-test
  needs:
    - job: build_for_integration_test
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-integration:1.0
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-integration0"
    paths:
      - $CI_PROJECT_DIR/tests/integration/report.html
      - $CI_PROJECT_DIR/tests/integration/dockerd.log
      - $CI_PROJECT_DIR/tests/integration/assets/*
  script:
    - pwd && echo $CI_PROJECT_DIR && echo ${CI_COMMIT_SHA}
    - 'python3 tests/integration/mqdb-ci-runner.py --hash-test --hash-test-total 3 --hash-test-num 0 --exclude-test-list-file tests/integration/exclude_test.list -n 2 "--timeout=300 --log-level=INFO --log-file-level=INFO" --runner-image-version 1.8.4 ||:'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_IN_K8S == "false"' # Trigger pipline during scheduled tasks
    - if: $CI_MERGE_REQUEST_LABELS == "test-integration"

integration_test1:
  stage: failover-test
  needs:
    - job: build_for_integration_test
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-integration:1.0
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-integration1"
    paths:
      - $CI_PROJECT_DIR/tests/integration/report.html
      - $CI_PROJECT_DIR/tests/integration/dockerd.log
      - $CI_PROJECT_DIR/tests/integration/assets/*
  script:
    - pwd && echo $CI_PROJECT_DIR && echo ${CI_COMMIT_SHA}
    - 'python3 tests/integration/mqdb-ci-runner.py --hash-test --hash-test-total 3 --hash-test-num 1 --exclude-test-list-file tests/integration/exclude_test.list -n 2 "--timeout=300 --log-level=INFO --log-file-level=INFO" --runner-image-version 1.8.4 ||:'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_IN_K8S == "false"' # Trigger pipline during scheduled tasks
    - if: $CI_MERGE_REQUEST_LABELS == "test-integration"

integration_test2:
  stage: failover-test
  needs:
    - job: build_for_integration_test
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-integration:1.0
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-integration2"
    paths:
      - $CI_PROJECT_DIR/tests/integration/report.html
      - $CI_PROJECT_DIR/tests/integration/dockerd.log
      - $CI_PROJECT_DIR/tests/integration/assets/*
  script:
    - pwd && echo $CI_PROJECT_DIR && echo ${CI_COMMIT_SHA}
    - 'python3 tests/integration/mqdb-ci-runner.py --hash-test --hash-test-total 3 --hash-test-num 2 --exclude-test-list-file tests/integration/exclude_test.list -n 2 "--timeout=300 --log-level=INFO --log-file-level=INFO" --runner-image-version 1.8.4 ||:'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_IN_K8S == "false"' # Trigger pipline during scheduled tasks
    - if: $CI_MERGE_REQUEST_LABELS == "test-integration"
