####################################### PERFORMANCE TESTS ####################################
performance_test0:
  stage: performance-test
  needs:
    - job: build_binary
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-performance:3.0.0
  parallel:
    matrix:
      - TOTAL_HASH_TEST_NUM: 3
        HASH_TEST_NUM: [0, 1, 2]
  tag:
    - HASH_SPLIT_TEST_${HASH_TEST_NUM}
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-performance0"
    paths:
      - $CI_PROJECT_DIR/docker/test/myscale_performance/test_output
  script:
    - pwd && echo $CI_PROJECT_DIR && echo ${CI_COMMIT_SHA}
    - docker/myscale_test_script/performance-test.sh CI_TEST_IN_K8S ${CI_COMMIT_SHA} $HASH_TEST_NUM
    - ls -al artifacts
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_IN_K8S == "false" && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH' # Trigger pipline during scheduled tasks
    - if: '$CI_MERGE_REQUEST_LABELS =~ /test-performance/'
