######################################## INTEGRATION TESTS ###################################
integration_test:
  stage: failover-test
  needs:
    - job: build_for_integration_test
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-integration-runner:3.0.0
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-integration$HASH_TEST_NUM"
    paths:
      - $CI_PROJECT_DIR/tests/integration/report.html
      - $CI_PROJECT_DIR/tests/integration/assets/*
  parallel:
    matrix:
      - TOTAL_HASH_TEST_NUM: 6
        HASH_TEST_NUM: [0, 1, 2, 3, 4, 5]
  tag:
    - HASH_SPLIT_TEST_${HASH_TEST_NUM}
  script:
    - pwd && echo $CI_PROJECT_DIR && echo ${CI_COMMIT_SHA}
    - cd tests/integration/ && python3 mqdb-ci-runner.py 
      --hash-test --run-in-docker 
      --harbor-user "$(echo $HARBOR_USER_B64 | base64 -d)" --harbor-password "$HARBOR_PASSWORD" 
      --hash-test-total $TOTAL_HASH_TEST_NUM --hash-test-num $HASH_TEST_NUM 
      --exclude-test-list-file exclude_test.list "--timeout=300 --log-level=INFO --log-file-level=INFO" || true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_IN_K8S == "false"'
    - if: '$CI_MERGE_REQUEST_LABELS =~ /test-integration/'
