image: harbor.internal.moqi.ai/mqdb/builder:3.0.0

# workflow:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#     - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
#     - if: "$CI_COMMIT_TAG"
#     - if: '$CI_PIPELINE_SOURCE == "schedule"'



.init-docker: &init-docker
  - chmod +x docker/builder/tools/docker-info.sh
  - docker/builder/tools/docker-info.sh
  - echo $HARBOR_PASSWORD | docker login harbor.internal.moqi.ai --username "$(echo $HARBOR_USER_B64 | base64 -d)" --password-stdin
  - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  - chmod +x docker/builder/tools/docker-buildx.sh
  - docker/builder/tools/docker-buildx.sh

.init-ssh: &init-ssh
  - ssh-keyscan -H git.moqi.ai >> ~/.ssh/known_hosts
  - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  - cp $BUILDER_PRIVATE_SSH_KEY ~/.ssh/id_rsa
  - cp $BUILDER_PUBLIC_SSH_KEY ~/.ssh/id_rsa.pub

stages:
  - package
  - harbor_image
  - docker_hub_image

build_package:
  stage: package
  before_script:
    - *init-ssh
  variables:
    KUBERNETES_CPU_REQUEST: 8
    KUBERNETES_CPU_LIMIT: 32
    KUBERNETES_MEMORY_REQUEST: 16Gi
    KUBERNETES_MEMORY_LIMIT: 32Gi
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    paths:
      - artifacts/*.tgz
  retry: 2
  script:
    - docker/builder/tools/submodule-update.sh
    - docker/builder/build.py --output artifacts --build-type RelWithDebInfo --profile release --arch linux-x86_64 --package --compiler "clang-15"
    - docker/builder/build.py --output artifacts --build-type RelWithDebInfo --profile release --arch linux-aarch64 --package --compiler "clang-15"

build_harbor_image:
  stage: harbor_image
  tags:
    - task
  dependencies: ["build_package"]
  before_script:
    - *init-docker
  script:
    - ls -lh artifacts/clickhouse-*.tgz
    - chmod +x docker/builder/tools/harbor-image.sh
    - docker/builder/tools/harbor-image.sh "$(echo $HARBOR_USER_B64 | base64 -d)" $HARBOR_PASSWORD


build_docker_hub_image:
  stage: docker_hub_image
  tags:
    - task
  dependencies: ["build_package"]
  before_script:
    - *init-docker
  script:
    - ls -lh artifacts/clickhouse-*.tgz
    - chmod +x docker/builder/tools/docker-hub-image.sh
    - docker/builder/tools/docker-hub-image.sh $DOCKERHUB_USERNAME $DOCKERHUB_PASSWORD
  rules:
    - if: $CI_COMMIT_TAG
    - when: manual
      allow_failure: true

