.no-proxy: &no-proxy
  - export http_proxy="" https_proxy=""

######################################## VECTOR TESTS ########################################
######### VECTOR TESTS ###########
vector_search_test:
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-stateless:3.0.0
  stage: functional-test
  needs:
    - job: build_binary
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-vector-test"
    paths:
      - $CI_PROJECT_DIR/docker/test/myscale_stateless/test_output
    when: always
  tags:
    - amd64
  before_script:
    - if [[ -f previous_pipeline_status.txt ]]; then
      exit 0;
      fi
    - *no-proxy
  script:
    - docker/myscale_test_script/stateless-test.sh true
    - docker/myscale_test_script/check-job-states.sh myscale_stateless
  rules:
    - if: '$CI_TEST_IN_K8S == "false"'
      changes:
        - src/**/*
        - tests/**/*
        - contrib/**/*
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true

###################################### FUNCTIONAL TESTS ######################################
### FUNCTIONAL STATELESS TESTS ###
# TODO Split stateless/stateful tests pipline
stateless_test:
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-stateless:3.0.0
  stage: functional-test
  needs:
    - job: build_binary
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-stateless-test"
    paths:
      - $CI_PROJECT_DIR/docker/test/myscale_stateless/test_output
    when: always
  parallel:
    matrix:
      - RUN_BY_HASH_TOTAL: 2
        RUN_BY_HASH_NUM: [0, 1]
  tags:
    - amd64
  before_script:
    - if [[ -f previous_pipeline_status.txt ]]; then
      exit 0;
      fi
    - *no-proxy
  script:
    - docker/myscale_test_script/stateless-test.sh
    - docker/myscale_test_script/check-job-states.sh myscale_stateless
  rules:
    - if: '$CI_TEST_IN_K8S == "false"'
      changes:
        - src/**/*
        - tests/**/*
        - contrib/**/*
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true

### FUNCTIONAL STATEFUL TESTS ####
stateful_test:
  image: harbor.internal.moqi.ai/mqdb/mqdb-test-stateless:3.0.0
  stage: functional-test
  needs:
    - job: build_binary
      artifacts: true
    - job: check_pipeline_already_running
      artifacts: true
  artifacts:
    name: "mqdb-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-stateful-test"
    paths:
      - $CI_PROJECT_DIR/docker/test/myscale_stateful/test_output
    when: always
  tags:
    - amd64
  before_script:
    - if [[ -f previous_pipeline_status.txt ]]; then
      exit 0;
      fi
    # - *no-proxy
  script:
    - docker/myscale_test_script/stateful-test.sh
    - docker/myscale_test_script/check-job-states.sh myscale_stateful
  rules:
    - if: '$CI_TEST_IN_K8S == "false"'
      changes:
        - src/**/*
        - tests/**/*
        - contrib/**/*
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
