[package]
name = "supercrate"
version = "0.1.0"
authors = ["MochiXu <mochix@myscale.com>"]
edition = "2021"

[dependencies]
blake3 ={ path = "libs/blake3"}
skim ={ path = "libs/skim"}
tantivy_search ={ path = "libs/tantivy_search"}


[lib]
crate-type = ["staticlib"]

