cmake_minimum_required(VERSION 3.22)

project(SUPERCRATE_RS)


if(NOT BUILD_RUST_FOR_CK)
    add_subdirectory(contrib ${CMAKE_CURRENT_BINARY_DIR}/contrib)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Release")
    set(RUST_PROFILE release)
elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set(RUST_PROFILE relwithdebinfo)
elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(RUST_PROFILE release)
else()
    set(RUST_PROFILE release)
endif()


if(BUILD_RUST_FOR_CK)
    message(STATUS "import Cargo.toml with profile: ${RUST_PROFILE}")
    # clickhouse_import_crate(MANIFEST_PATH Cargo.toml PROFILE ${RUST_PROFILE})
    corrosion_import_crate(NO_STD MANIFEST_PATH "Cargo.toml" PROFILE "release")
else()
    corrosion_import_crate(NO_STD MANIFEST_PATH "Cargo.toml" PROFILE ${RUST_PROFILE})
endif()


set(rust_lib "supercrate")


# --------------------------------------------------------------------------------------------------- #
# corrosion 2022 edition doesn't fit this CMake.
# For corrosion 2022, should use `set(cxx_bridge_binary_folder ${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/cargo/build/${Rust_CARGO_TARGET_CACHED}/cxxbridge)`
# --------------------------------------------------------------------------------------------------- #
set(cxx_bridge_binary_folder ${CMAKE_BINARY_DIR}/cargo/build/${Rust_CARGO_TARGET_CACHED}/cxxbridge)
set(bridge_module_names "skim" "tantivy_search" "sparse_index")



# --------------------------------------------------------------------------------------------------- #
# -Wno-dollar-in-identifier-extension: cxx bridge complies names with '$'
# -Wno-unused-macros: unused CXXBRIDGE1_RUST_STRING
# --------------------------------------------------------------------------------------------------- #
set(CXXBRIDGE_CXXFLAGS "-Wno-dollar-in-identifier-extension -Wno-unused-macros")
set(RUST_CXXFLAGS "${RUST_CXXFLAGS} ${CXXBRIDGE_CXXFLAGS}")



# --------------------------------------------------------------------------------------------------- #
# Config each submodule which is built using `cxx_bridge`.
# --------------------------------------------------------------------------------------------------- #
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/.cargo/config.toml.in" "${CMAKE_CURRENT_SOURCE_DIR}/.cargo/config.toml" @ONLY)
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/build.rs.in" "${CMAKE_CURRENT_SOURCE_DIR}/build.rs" @ONLY)

foreach(module ${bridge_module_names})
    # Configure .cargo/config.toml files
    configure_file(
        "${CMAKE_CURRENT_SOURCE_DIR}/libs/${module}/.cargo/config.toml.in"
        "${CMAKE_CURRENT_SOURCE_DIR}/libs/${module}/.cargo/config.toml"
        @ONLY
    )

    # Configure build.rs files
    configure_file(
        "${CMAKE_CURRENT_SOURCE_DIR}/libs/${module}/build.rs.in"
        "${CMAKE_CURRENT_SOURCE_DIR}/libs/${module}/build.rs"
        @ONLY
    )
endforeach()



# --------------------------------------------------------------------------------------------------- #
# Collect headers and sources generated by `cxx_bridge` (corrosion).
# --------------------------------------------------------------------------------------------------- #
# Collect headers from all submodules.
set(bridge_includes ${cxx_bridge_binary_folder}/rust ${CMAKE_CURRENT_SOURCE_DIR}/include)
# Collect source files from all submodules that are built using `cxx_bridge`, excluding those compile with `cbindgen`.
set(bridge_sources ${cxx_bridge_binary_folder}/rust/cxx.h)
set(file_name "src/lib.rs")
foreach(module ${bridge_module_names})
    set(${module}_bridge
        "${cxx_bridge_binary_folder}/${module}/${file_name}.h"
        "${cxx_bridge_binary_folder}/${module}/${file_name}.cc"
    )
    message("🍀 collect -> ${module}: ${${module}_bridge}")
    list(APPEND bridge_sources ${${module}_bridge})
endforeach()



add_custom_command(
    OUTPUT
    ${bridge_includes}
    ${bridge_sources}
    COMMAND
    DEPENDS ${rust_lib}-static
    # DEPENDS cargo-build_supercrate  # releated with corrosion version.
    COMMENT "Fixing cmake to find source files"
)


# --------------------------------------------------------------------------------------------------- #
# Add library.
# --------------------------------------------------------------------------------------------------- #
add_library(${rust_lib}_cxxbridge
    ${bridge_includes}
    ${bridge_sources}
)
# cxx bridge compiles such bindings
set_target_properties(${rust_lib}_cxxbridge PROPERTIES COMPILE_FLAGS "${CXXBRIDGE_CXXFLAGS}")
set_target_properties(${rust_lib}_cxxbridge PROPERTIES LINKER_LANGUAGE CXX)

target_include_directories(${rust_lib}_cxxbridge
    PUBLIC
    ${bridge_includes}
)


#-Wno-dollar-in-identifier-extension -Wno-unused-macros
target_compile_options(${rust_lib}_cxxbridge PUBLIC -Wno-dollar-in-identifier-extension)
target_compile_options(${rust_lib}_cxxbridge PUBLIC -Wno-unused-macros)


# Create total target with alias with given namespace
add_library(${rust_lib}-total INTERFACE)
target_link_libraries(${rust_lib}-total
    INTERFACE
    ${rust_lib}_cxxbridge
    ${rust_lib}
)

# for end-user to link into project
add_library(ch_rust::${rust_lib} ALIAS ${rust_lib}-total)

if(NOT BUILD_RUST_FOR_CK)
    add_subdirectory(integrate_cpp)
endif()
