import os

myscale_repo_config = {
    "url": "https://git.moqi.ai",
    "project_id": 202,
    "project_name": "mqdb",
}

myscale_deploy_guide_repo_config = {
    "url": "https://github.com/myscale/myscale-deploy-guide",
    "repo_name": "myscale-deploy-guide",
    "repo_git_path": "myscale/myscale-deploy-guide",
    "repo_ssh_url": "git@github.com:myscale/myscale-deploy-guide.git",
    "default_branch": "main",
    "release_note_file": "db-release.md",
}


CUR_PATH = os.path.split(os.path.realpath(__file__))[0]
REPO_PATH = os.path.join(CUR_PATH[: CUR_PATH.find("ClickHouse")], "ClickHouse")
MYSCALE_VERSION_FILE = os.path.join(REPO_PATH, "cmake/autogenerated_myscale_versions.txt")
CHANGELOG_PATH = os.path.join(REPO_PATH, "MYSCALE_CHANGELOG.md")
NO_CHGLOG_LABEL = "no-chglog"
MYSCALE_DEFAULT_BRANCH = "mqdb-dev"
