# package sources should be placed in ${PWD}/root
# nfpm should run from the same directory with a config
name: "clickhouse-keeper-dbg"
arch: "${ARCH}" # amd64, arm64
platform: "linux"
version: "${VERSION_STRING}"
vendor: "ClickHouse Inc."
homepage: "https://clickhouse.com"
license: "Apache"
section: "database"
priority: "optional"
maintainer: "ClickHouse Dev Team <packages+linux@clickhouse.com>"
description: |
  debugging symbols for clickhouse-keeper
    This package contains the debugging symbols for clickhouse-keeper.

contents:
  - src: usr/lib/debug/usr/bin/clickhouse-keeper.debug
    dst: /usr/lib/debug/usr/bin/clickhouse-keeper.debug
  # docs
  - src: usr/share/doc/clickhouse/LICENSE
    dst: /usr/share/doc/clickhouse-keeper-dbg/LICENSE
  - src: usr/share/doc/clickhouse/NOTICE.txt
    dst: /usr/share/doc/clickhouse-keeper-dbg/NOTICE.txt
