# package sources should be placed in ${PWD}/root
# nfpm should run from the same directory with a config
name: "clickhouse-client"
arch: "${ARCH}" # amd64, arm64
platform: "linux"
version: "${VERSION_STRING}"
vendor: "ClickHouse Inc."
homepage: "https://clickhouse.com"
license: "Apache"
section: "database"
priority: "optional"

replaces:
  - clickhouse-compressor
conflicts:
  - clickhouse-compressor

maintainer: "ClickHouse Dev Team <packages+linux@clickhouse.com>"
description: |
  Client binary for ClickHouse
    ClickHouse is a column-oriented database management system.
    that allows generating analytical data reports in real time.
    This package provides clickhouse-client, clickhouse-local and clickhouse-benchmark.

overrides:
  deb:
    depends:
      - clickhouse-common-static (= ${VERSION_STRING})
  rpm:
    depends:
      - clickhouse-common-static = ${VERSION_STRING}

contents:
  - src: etc/clickhouse-client/config.xml
    dst: /etc/clickhouse-client/config.xml
    type: config
  - src: usr/bin/clickhouse-benchmark
    dst: /usr/bin/clickhouse-benchmark
  - src: usr/bin/clickhouse-compressor
    dst: /usr/bin/clickhouse-compressor
  - src: usr/bin/clickhouse-format
    dst: /usr/bin/clickhouse-format
  - src: usr/bin/clickhouse-client
    dst: /usr/bin/clickhouse-client
  - src: usr/bin/clickhouse-local
    dst: /usr/bin/clickhouse-local
  - src: usr/bin/clickhouse-obfuscator
    dst: /usr/bin/clickhouse-obfuscator
  # docs
  - src: usr/share/doc/clickhouse/LICENSE
    dst: /usr/share/doc/clickhouse-client/LICENSE
  - src: usr/share/doc/clickhouse/NOTICE.txt
    dst: /usr/share/doc/clickhouse-client/NOTICE.txt
