# package sources should be placed in ${PWD}/root
# nfpm should run from the same directory with a config
name: "clickhouse-server"
arch: "${ARCH}" # amd64, arm64
platform: "linux"
version: "${VERSION_STRING}"
vendor: "ClickHouse Inc."
homepage: "https://clickhouse.com"
license: "Apache"
section: "database"
priority: "optional"

conflicts:
  - clickhouse-keeper
depends:
  - adduser
replaces:
  - clickhouse-server-common
  - clickhouse-server-base
provides:
  - clickhouse-server-common
recommends:
  - libcap2-bin

maintainer: "ClickHouse Dev Team <packages+linux@clickhouse.com>"
description: |
  Server binary for ClickHouse
    ClickHouse is a column-oriented database management system
    that allows generating analytical data reports in real time.
    This package provides clickhouse common configuration files

overrides:
  deb:
    depends:
      - clickhouse-common-static (= ${VERSION_STRING})
  rpm:
    depends:
      - clickhouse-common-static = ${VERSION_STRING}

contents:
  - src: etc/clickhouse-server
    dst: /etc/clickhouse-server
    type: config
  - src: clickhouse-server.service
    dst: /lib/systemd/system/clickhouse-server.service
  - src: usr/bin/clickhouse-copier
    dst: /usr/bin/clickhouse-copier
  - src: clickhouse
    dst: /usr/bin/clickhouse-keeper
    type: symlink
  - src: usr/bin/clickhouse-report
    dst: /usr/bin/clickhouse-report
  - src: usr/bin/clickhouse-server
    dst: /usr/bin/clickhouse-server
  # docs
  - src: usr/share/doc/clickhouse/LICENSE
    dst: /usr/share/doc/clickhouse-server/LICENSE
  - src: usr/share/doc/clickhouse/NOTICE.txt
    dst: /usr/share/doc/clickhouse-server/NOTICE.txt

scripts:
  postinstall: ./clickhouse-server.postinstall
